DROP TABLE ZA_LABEL;
DROP TABLE ZA_CHAPTER;
DROP TABLE ZA_METACONTENT;

CREATE COLUMN TABLE "SYSTEM"."ZA_METACONTENT"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  TITLE VARCHAR(100),
  AUTHOR VARCHAR(100)
);

CREATE COLUMN TABLE "SYSTEM"."ZA_LABEL"
(
  DOCUMENT_ID INTEGER CS_INT,
  LABEL_NAME VARCHAR(50),
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);

CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
