DROP TABLE ZA_LABEL;
DROP TABLE ZA_CHAPTER;
DROP TABLE ZA_METACONTENT;
DROP TABLE ZA_CHAPTER_1;
DROP TABLE ZA_CHAPTER_2;
DROP TABLE ZA_CHAPTER_3;
DROP TABLE ZA_CHAPTER_4;
DROP TABLE ZA_CHAPTER_5;
DROP TABLE ZA_CHAPTER_6;
DROP TABLE ZA_CHAPTER_7;
DROP TABLE ZA_CHAPTER_8;
DROP TABLE ZA_CHAPTER_9;
DROP TABLE ZA_CHAPTER_10;
DROP TABLE ZA_CHAPTER_11;
DROP TABLE ZA_CHAPTER_12;
DROP TABLE ZA_CHAPTER_13;
DROP TABLE ZA_CHAPTER_14;

CREATE COLUMN TABLE "SYSTEM"."ZA_METACONTENT"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  TITLE VARCHAR(100),
  AUTHOR VARCHAR(100)
);

CREATE COLUMN TABLE "SYSTEM"."ZA_LABEL"
(
  DOCUMENT_ID INTEGER CS_INT,
  LABEL_NAME VARCHAR(50),
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);

CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);


CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_1"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_2"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_3"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_4"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_5"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_6"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_7"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_8"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_9"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_10"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_11"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_12"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_13"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);
CREATE COLUMN TABLE "SYSTEM"."ZA_CHAPTER_14"
(
  DOCUMENT_ID INTEGER CS_INT PRIMARY KEY,
  "FULLTEXT" CLOB MEMORY THRESHOLD 1000,
  FOREIGN KEY("DOCUMENT_ID") REFERENCES "SYSTEM"."ZA_METACONTENT"
);